# These functions were based on the functions created by Mario Castro-Gama to test crew allocation and
# generating INP files with controls to close/open pipes

def allocate_crews(reparations, dmatrix, indexes, n_teams):
    missing_repairs = set(indexes) - set(reparations)
    if missing_repairs:
        raise KeyError(f"IDs missing from reparations: {sorted(missing_repairs)}")

    missing_matrix = set(indexes) - set(dmatrix.index)
    if missing_matrix:
        raise KeyError(f"IDs missing from travel-time matrix: {sorted(missing_matrix)}")

    # existing allocation logic...
    """
    allocate_crews(reparations, dmatrix, indexes, n_teams):
    
    Description
       This is essentially a greedy load-balancing problem: 
       process jobs in the order given by indexes, and always assign the next job 
       to the crew with the smallest accumulated repair time.
    
    Input Parameters
    -----------------
    reparations : dict
        Dictionary {id: repair_time}
    dmatrix : dict
        Dictionary {id_i: {id_j: travel_time}}
    indexes : list
        List of ids indicating the allocation order, must have the same length of the keys of 'reparations'
    n_teams : int
        Number of crews, how many crews are you sending in the field to repair pipes

    Output / Returns
    ----------------
    dictionary with the pipe ids and the times of interventions for each crew. 
    dict { 'crew_1': { 'pipe_ids': [...], 'time_total': ...},
           'crew_2': { 'pipe_ids': [...], 'time_total': ...}, 
           ...
         }

    Developed by : Mario Castro-Gama, ir. MSc. PhD
    Last update  : 2026-05-20
                   2026-06-15, added travel time constant
                   2026-07-21, added travel tiem as function of 'dmatrix' distance matrix
    
    """

    # if each crew key is a string
    # crews = { f"crew_{i+1}": {'pipe_ids':  [], 
    #                           'time_k':    [], 
    #                           'time_t':    [], 
    #                           'time_0':    [],
    #                           'time_1':    [],
    #                           'time_total': 0,
    #                          } for i in range(n_teams)}

    # if each crew key is an int (starting at 1)
    crews = { i+1: {'pipe_ids':  [], 
                    'time_repair':    [], 
                    'time_travel':   [],
                    'time_0':    [],
                    'time_1':    [],
                    'time_total': 0,
                   } for i in range(n_teams)}

    nrep = len(reparations)

    print('')
    print('organize distances for each crew')
    new_controls = []
    for idx in indexes:
        if idx not in reparations:
            raise KeyError(f"Pipe ID '{idx}' not found in reparations")

        # Find the crew with the minimum accumulated time to allocate the next reparation
        # first available gets chosen
        crew_curr = min(crews, key = lambda c: crews[c]['time_total'])

        # current reparation time
        repair_time = reparations[idx]['t_r']

        # find the travel time between this pipe and the previous one
        if crews[crew_curr]['pipe_ids']==[]:
            travel_time = 0.5  # no previous pipe so give it 30 minutes
        else:
            # This is estimated from distance matrix 'dmatrix', that matrix is square and static for each damage scenario
            pipe_prev = crews[crew_curr]['pipe_ids'][-1]
            travel_time = dmatrix[pipe_prev][idx]
            print('Crew '+str(crew_curr)+', from '+pipe_prev+'-to-'+idx+' : '+str(travel_time))
        
        # Assign the reparation to each crew
        crews[crew_curr]['pipe_ids'].append(idx)
        crews[crew_curr]['time_repair'].append(repair_time)
        crews[crew_curr]['time_travel'].append(travel_time)
        crews[crew_curr]['time_0'].append(travel_time + crews[crew_curr]['time_total'])
        crews[crew_curr]['time_1'].append(repair_time + crews[crew_curr]['time_0'][-1])
        crews[crew_curr]['time_total'] += repair_time + travel_time

        new_controls.append(f"; Crew {crew_curr} - Pipe {idx}\n")
        new_controls.append(f"LINK {idx}_A CLOSED AT TIME {crews[crew_curr]['time_0'][-1]}\n") # close Pipe_id_<A> when arriving to the location
        new_controls.append(f"LINK {idx}_B CLOSED AT TIME {crews[crew_curr]['time_0'][-1]}\n") # close Pipe_id_<B> when arriving to the location
        new_controls.append(f"LINK {idx} OPEN AT TIME {crews[crew_curr]['time_1'][-1]}\n")     # Open Pipe_id only after time of reparation
        
    return crews, new_controls

import os


def write_inp_controls(input_inp, output_inp, crews, new_controls):
    """
    Creates a new EPANET INP file using the control rules generated by
    allocate_crews().

    Parameters
    ----------
    input_inp : str
        Path to the original damaged INP file.

    output_inp : str
        Path where the modified INP file will be saved.

    crews : dict
        Crew allocation dictionary returned by allocate_crews().
        (Currently only stored for compatibility and future extensions.)

    new_controls : list of str
        List of EPANET control lines generated by allocate_crews().

    Returns
    -------
    str
        Path to the generated INP file.
    """

    # Basic checks
    if not os.path.exists(input_inp):
        raise FileNotFoundError(f"Input file not found:\n{input_inp}")

    if not isinstance(new_controls, list):
        raise TypeError("new_controls must be a list of strings.")

    if len(new_controls) == 0:
        raise ValueError("new_controls is empty.")

    # Read original INP
    with open(input_inp, "r") as f:
        lines = f.readlines()

    # Locate [CONTROLS]
    controls_start = None

    for i, line in enumerate(lines):
        if line.strip().upper() == "[CONTROLS]":
            controls_start = i
            break

    # If [CONTROLS] does not exist, create it
    if controls_start is None:

        if lines[-1].strip() != "":
            lines.append("\n")

        lines.append("[CONTROLS]\n")
        controls_start = len(lines) - 1

        controls_end = len(lines)

    else:

        # Find the next section
        controls_end = len(lines)

        for j in range(controls_start + 1, len(lines)):

            txt = lines[j].strip()

            if txt.startswith("[") and txt.endswith("]"):
                controls_end = j
                break

    # Build new CONTROLS section
    control_block = [
        "[CONTROLS]\n",
    #    "; ---------------------------------------------------------\n",
    #    "; Restoration controls generated automatically\n",
    #    "; ---------------------------------------------------------\n",
    ]

    for control in new_controls:

        control = control.rstrip()

        if control != "":
            control_block.append(control + "\n")

    control_block.append("\n")

    # Replace old CONTROLS section
    new_lines = (
        lines[:controls_start]
        + control_block
        + lines[controls_end:]
    )

    # Save new INP
    with open(output_inp, "w") as f:
        f.writelines(new_lines)

    print("=" * 60)
    print("Restoration INP successfully created.")
    print(f"Output file : {output_inp}")
    print(f"Controls    : {len(new_controls)}")
    print("=" * 60)

    return output_inp